language: node_js
node_js:
  - stable
install:
  - npm install
deploy:
  skip_cleanup: true
  provider: heroku
  app: api-hic
  api_key:
    secure: iQYOMtAzB0PuMqRZ7bVqr3V8xvwoGsDvxPjLGSBZ5KzcxfC7QCkRJfyfAJVErqmMGnXMbag0cd6Et2hzt9eflCfBH4jNGTgrMRVTrFj+ARUvF8ngtCjQRXP3996sknH1D7WEs2U3RbehFrDrZwnc+MltuswcGuXpYlof6uxCQEkiQNYZlOHCOdILU11ftcRiZc2kWyNCKMJn4PxLNHBCGAd+7/oVehHTHZ9u9PApJ0oBWnX19xISMt8qN+xpY9WlBSNugKODYmmI3L9eALas9gbh3TJZe0dUroV24gRSvAP6NmtpgtFTc5+l4f3OCI183bZz2V5m1Q19tZzdf3/uknVr33Djfe1CBR2VGs9lRQtuGyLURuZKGM5F7hN7zBnGcipClesHcXMzW8TEBPfDRmwp7RA5QezcPnMJVNuydkFtzITTnSziZBnB4RB9BFFIzDNohsZZ4b0OnnnC5G5eivkat2TPGTdLJSDKfjmfxZIMuGa6kGZpCcpkZdRPL9xrky+NAYFC7M52lzxd9krUHmDQ3X/dPBru+YPMQ8F5xbAfVk9BBBXlvqLu15nUM8RHBSCv+LSpdz5s2rJG5pFlC7r0Cb/+eMaNYb4OhnWt7pFDWvtlFY07B63d8LuCeBxrTSNl5oJuJlznDhYefV95VU0XFFmPjFwhtzug8zpSHCE=

